-- Generated by the Omarchy Workspace Layout plugin. Do not edit.
-- Your layouts and profiles live in ~/.config/omarchy/workspace-layout.json;
-- this file is rewritten from that document every time it changes.
--
-- Active profile: default

local W = _G.__omarchy_wsl
if not W then W = { registered = {}, rules = {} }; _G.__omarchy_wsl = W end
-- Added after the first release: a compositor still running the older
-- runtime has a W without this table, and reload must not lose its rules.
W.app_rules = W.app_rules or {}
W.specs = {}
-- workspace -> class -> the places that class wants there. Per workspace,
-- because the same app pinned to slot 1 of one workspace must not claim
-- slot 1 of every other workspace it happens to open on.
W.slots = {}

local function normalize(weights)
  local total = 0
  for i = 1, #weights do total = total + weights[i] end
  local out = {}
  if total <= 0 then
    for i = 1, #weights do out[i] = 100 / #weights end
    return out
  end
  for i = 1, #weights do out[i] = weights[i] * 100 / total end
  return out
end

-- A part is either a plain cross weight or a table saying how wide it is and
-- how it is cut along the grain again.
local function part_weight(part)
  if type(part) == "table" then return part.weight end
  return part
end

local function part_split(part)
  if type(part) == "table" and part.parts then return part.parts end
  return {}
end

local function part_pieces(part)
  local split = part_split(part)
  if #split > 1 then return #split end
  return 1
end

-- Even parts for a slot: what overflow stacking falls back to when it adds
-- parts to a slot whose ratio was drawn for fewer of them.
local function even_cell(count)
  local out = {}
  for i = 1, count do out[i] = 100 / count end
  return out
end

local function orient(orientation, main_offset, main_size, cross_offset, cross_size)
  if orientation == "rows" then
    return { cross_offset, main_offset, cross_size, main_size }
  end
  return { main_offset, cross_offset, main_size, cross_size }
end

local function grid_rects(spec, n)
  local columns
  if spec.grid_columns and spec.grid_columns > 0 then
    columns = math.min(spec.grid_columns, n)
  else
    columns = math.ceil(math.sqrt(n))
  end
  local rows = math.ceil(n / columns)
  local rects = {}
  for row = 0, rows - 1 do
    local first = row * columns
    local in_row = math.min(columns, n - first)
    for col = 0, in_row - 1 do
      local right = (col == in_row - 1) and 1 or (col + 1) / in_row
      local bottom = (row == rows - 1) and 1 or (row + 1) / rows
      rects[#rects + 1] = { col / in_row, row / rows, right - col / in_row, bottom - row / rows }
    end
  end
  return rects
end

-- Widest slot first, so the first window lands in the main area rather than
-- in a sliver at the edge. Ties keep positional order. table.sort is not
-- stable in Lua, hence the explicit index tiebreak.
local function fill_order(weights)
  local index = {}
  for i = 1, #weights do index[i] = i end
  table.sort(index, function(a, b)
    if weights[a] ~= weights[b] then return weights[a] > weights[b] end
    return a < b
  end)
  return index
end

local function ratio_rects(spec, n)
  local weights = spec.weights
  local counts = spec.cells
  local k = #weights
  local primary, subs = {}, {}
  local base = 0
  for i = 1, k do
    for j = 1, #counts[i] do base = base + part_pieces(counts[i][j]) end
  end
  -- A layout with a split slot was drawn in two dimensions and holds: there
  -- is no sensible way to grow one of its halves into the missing window.
  local split = base > k

  if n <= base and (spec.underfill == "hold" or split) then
    for i = 1, k do primary[i] = weights[i]; subs[i] = counts[i] end
  elseif n <= base then
    local chosen = {}
    local priority = fill_order(weights)
    for i = 1, n do chosen[i] = priority[i] end
    table.sort(chosen)
    for i = 1, n do primary[i] = weights[chosen[i]]; subs[i] = { 100 } end
  elseif spec.overflow == "extend" then
    for i = 1, k do primary[i] = weights[i]; subs[i] = counts[i] end
    local grown = base
    while grown < n do
      primary[#primary + 1] = weights[k]
      subs[#subs + 1] = { 100 }
      grown = grown + 1
    end
  else
    for i = 1, k do primary[i] = weights[i]; subs[i] = counts[i] end
    local at = (spec.overflow == "first") and 1 or k
    local held = 0
    for i = 1, #subs[at] do held = held + part_pieces(subs[at][i]) end
    subs[at] = even_cell(held + n - base)
  end

  primary = normalize(primary)

  local cells, cell_slot = {}, {}
  local offset = 0
  for slot = 1, #primary do
    local size = primary[slot] / 100
    if slot == #primary then size = 1 - offset end
    local list = subs[slot]
    local weights_of = {}
    for s = 1, #list do weights_of[s] = part_weight(list[s]) end
    local parts = normalize(weights_of)
    local crossed = 0
    for s = 1, #parts do
      local sub_size = parts[s] / 100
      if s == #parts then sub_size = 1 - crossed end
      local split = part_split(list[s])
      if #split > 1 then
        -- The part is cut again, back along the grain.
        local inner = normalize(split)
        local run = 0
        for q = 1, #inner do
          local inner_size = size * inner[q] / 100
          if q == #inner then inner_size = size - run end
          cells[#cells + 1] = orient(spec.orientation, offset + run, inner_size, crossed, sub_size)
          cell_slot[#cell_slot + 1] = slot
          run = run + inner_size
        end
      else
        cells[#cells + 1] = orient(spec.orientation, offset, size, crossed, sub_size)
        cell_slot[#cell_slot + 1] = slot
      end
      crossed = crossed + sub_size
    end
    offset = offset + size
  end

  local order
  if spec.fill == "order" then
    order = {}
    for i = 1, #primary do order[i] = i end
  else
    order = fill_order(primary)
  end

  local rects = {}
  for i = 1, #order do
    for c = 1, #cells do
      if cell_slot[c] == order[i] then rects[#rects + 1] = cells[c] end
    end
  end
  -- Under "hold" there are more cells than windows; the surplus are the
  -- empty slots, and they are last because the list is in fill order.
  while #rects > n do table.remove(rects) end
  return rects
end

function W.rects(spec, n)
  if n <= 0 then return {} end
  if spec.kind == "grid" then return grid_rects(spec, n) end
  return ratio_rects(spec, n)
end

-- Which rect each window takes. W.rects hands them back in fill order —
-- the same order the canvas numbers its slots — so a targeted class is
-- simply an index into that list, and everyone else keeps the order
-- Hyprland handed them in, filling whatever is left.
--
-- A class holds a *list* of slots, so a second window of the same app takes
-- the next place on its list rather than fighting the first for one.
--
-- A slot nobody can have right now (a 3 with two windows open) is skipped
-- rather than held empty: the window falls back to its normal place.
function W.assign(targets, n)
  local out, taken = {}, {}
  for i = 1, n do
    local win = targets[i].window
    local wants = nil
    if win then
      local ok, class = pcall(function() return win.class end)
      local fine, ws = pcall(function() return win.workspace and win.workspace.id end)
      if ok and class and fine and ws then
        local here = W.slots[tostring(ws)]
        if here then wants = here[class] end
      end
    end
    if wants then
      for k = 1, #wants do
        local want = wants[k]
        if want >= 1 and want <= n and not taken[want] then
          out[i] = want
          taken[want] = true
          break
        end
      end
    end
  end
  local free = 1
  for i = 1, n do
    if not out[i] then
      while taken[free] do free = free + 1 end
      out[i] = free
      taken[free] = true
    end
  end
  return out
end

-- Convert fractions to pixels by rounding the *edges*, not the sizes, so
-- neighbouring windows always share an exact boundary and no seam of dead
-- pixels opens up between them.
function W.place(id, ctx)
  local n = #ctx.targets
  if n == 0 then return end
  local spec = W.specs[id]
  if not spec then return end
  local a = ctx.area
  local rects = W.rects(spec, n)
  local pick = W.assign(ctx.targets, n)
  for i = 1, n do
    local r = rects[pick[i]]
    if r then
      local x0 = math.floor(a.w * r[1] + 0.5)
      local y0 = math.floor(a.h * r[2] + 0.5)
      local x1 = math.floor(a.w * (r[1] + r[3]) + 0.5)
      local y1 = math.floor(a.h * (r[2] + r[4]) + 0.5)
      ctx.targets[i]:place({ x = a.x + x0, y = a.y + y0, w = x1 - x0, h = y1 - y0 })
    end
  end
end

-- Hyprland refuses a second registration under the same name, and this file
-- is re-run on every config reload, so registration is remembered for the
-- life of the compositor. Behaviour still updates: the closure reads
-- W.specs, which the reload has just replaced.
function W.register(id)
  local name = "omarchy-wsl-" .. id
  if W.registered[name] then return end
  W.registered[name] = true
  hl.layout.register(name, {
    recalculate = function(ctx) W.place(id, ctx) end,
    layout_msg = function(ctx, msg)
      if ctx then W.place(id, ctx) end
      return true
    end,
  })
end

-- Workspace rules accumulate: adding a second rule for a workspace does not
-- retire the first. Keep the handle so the previous rule can be disabled,
-- otherwise switching profiles would pile up dead rules that still win.
function W.set_workspace(ws, layout)
  local previous = W.rules[ws]
  if previous then pcall(function() previous:set_enabled(false) end) end
  W.rules[ws] = hl.workspace_rule({ workspace = ws, layout = layout })
end

-- App pins, as window rules. Unlike a workspace rule there is no fixed set
-- of keys to overwrite — a pin the user deleted simply is not in the new
-- file — so every rule this plugin owns is retired before the current set
-- is installed, and the table is rebuilt from scratch.
function W.reset_apps()
  for _, rule in pairs(W.app_rules) do
    pcall(function() rule:set_enabled(false) end)
  end
  W.app_rules = {}
end

-- `silent` keeps a window that opens while you are elsewhere from dragging
-- your view to its workspace, which is the whole point of pinning it there.
function W.set_slot(ws, class, slots)
  if not W.slots[ws] then W.slots[ws] = {} end
  W.slots[ws][class] = slots
end

function W.set_app(match, pattern, ws)
  W.app_rules[match] = hl.window_rule({
    name = "omarchy-wsl-pin-" .. match,
    match = { class = pattern },
    workspace = ws .. " silent",
  })
end

-- Nothing re-tiles a workspace just because its spec changed, so ask the
-- active layout to lay itself out again. Errors on a workspace running a
-- built-in layout, which has no idea what this message means.
function W.relayout()
  pcall(function() hl.dispatch(hl.dsp.layout("relayout")) end)
end

W.specs["even"] = { kind = "ratio", orientation = "columns", overflow = "extend", fill = "largest", underfill = "rescale", grid_columns = 0, cells = { { 100 }, { 100 } }, weights = { 50, 50 } }
W.specs["focus"] = { kind = "ratio", orientation = "columns", overflow = "last", fill = "largest", underfill = "hold", grid_columns = 0, cells = { { 100 }, { 100 }, { 100 } }, weights = { 25, 50, 25 } }
W.specs["main"] = { kind = "ratio", orientation = "columns", overflow = "last", fill = "largest", underfill = "rescale", grid_columns = 0, cells = { { 100 }, { 100 } }, weights = { 60, 40 } }
W.specs["main-right"] = { kind = "ratio", orientation = "columns", overflow = "first", fill = "largest", underfill = "rescale", grid_columns = 0, cells = { { 100 }, { 100 } }, weights = { 40, 60 } }
W.specs["golden"] = { kind = "ratio", orientation = "columns", overflow = "last", fill = "largest", underfill = "rescale", grid_columns = 0, cells = { { 100 }, { 100 } }, weights = { 61.8, 38.2 } }
W.specs["thirds"] = { kind = "ratio", orientation = "columns", overflow = "extend", fill = "largest", underfill = "rescale", grid_columns = 0, cells = { { 100 }, { 100 }, { 100 } }, weights = { 33.34, 33.33, 33.33 } }
W.specs["wide-centre"] = { kind = "ratio", orientation = "columns", overflow = "last", fill = "largest", underfill = "hold", grid_columns = 0, cells = { { 100 }, { 100 }, { 100 } }, weights = { 20, 60, 20 } }
W.specs["stacked"] = { kind = "ratio", orientation = "rows", overflow = "last", fill = "largest", underfill = "rescale", grid_columns = 0, cells = { { 100 }, { 100 } }, weights = { 50, 50 } }
W.specs["grid"] = { kind = "grid", orientation = "columns", overflow = "last", fill = "largest", underfill = "rescale", grid_columns = 0, cells = { { 100 }, { 100 } }, weights = { 50, 50 } }

W.register("even")
W.register("focus")
W.register("main")
W.register("main-right")
W.register("golden")
W.register("thirds")
W.register("wide-centre")
W.register("stacked")
W.register("grid")

W.set_workspace("1", "dwindle")
W.set_workspace("2", "dwindle")
W.set_workspace("3", "dwindle")
W.set_workspace("4", "dwindle")
W.set_workspace("5", "dwindle")
W.set_workspace("6", "dwindle")
W.set_workspace("7", "dwindle")
W.set_workspace("8", "dwindle")
W.set_workspace("9", "dwindle")
W.set_workspace("10", "dwindle")

W.reset_apps()
