#!/usr/bin/env bash
# Compile stock German NeoQwertz, then stop NumLock from selecting Neo layer 4.
# Omarchy turns NumLock on by default; stock Neo treats that as a layer lock,
# so letter keys become arrows/Home/Backspace. This file is safe to re-run.
set -euo pipefail

out="${1:-$HOME/.config/xkb/keymap/neoqwertz.xkb}"
mkdir -p "$(dirname "$out")"
tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

xkbcli compile-keymap --layout de,de --variant neo_qwertz, --options grp:alts_toggle >"$tmp"

python3 - "$tmp" "$out" <<'PY'
import re
import sys

src, dest = sys.argv[1], sys.argv[2]
text = open(src, encoding="utf-8").read()

def patch_type(match):
    block = match.group(0)
    if not re.search(r"map\[NumLock\]\s*=\s*5\s*;", block):
        return block
    # Drop NumLock mappings first. Stripping the word beforehand would turn
    # map[Shift+NumLock]=6 into a second map[Shift] and break Shift/letters.
    block = re.sub(r"^\s*(?:map|preserve)\[[^\]]*NumLock[^\]]*\][^\n]*\n", "", block, flags=re.M)

    def strip_mods(m):
        mods = re.sub(r"\+NumLock|NumLock\+", "", m.group(1))
        return f"modifiers= {mods};"

    return re.sub(r"modifiers= ([^;]*);", strip_mods, block, count=1)

patched, n = re.subn(
    r'type\s+"[^"]+"\s*\{.*?\n\t\};',
    patch_type,
    text,
    flags=re.S,
)
if n == 0:
    raise SystemExit("no xkb type blocks found")

header = (
    "// Generated by ~/.config/xkb/build-neoqwertz.sh\n"
    "// German NeoQwertz + plain German (Left Alt + Right Alt).\n"
    "// NumLock does not lock Neo layer 4, so letters stay typeable.\n"
)
open(dest, "w", encoding="utf-8").write(header + patched)
print(f"wrote {dest}")
PY
